server:
  port: 8085
  servlet:
    context-path: /
spring:
  application:
    name: spring-boot-demo
  datasource:
    name: db
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://121.43.39.85:3306/mambike_dealer?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&zeroDateTimeBehavior=convertToNull
    username: operator
    password: jndz2017
mybatis:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.wzy.boot.demo.model